# Generated by Django 6.0.2 on 2026-02-14 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Bot Ativo')),
                ('check_interval_seconds', models.IntegerField(default=60, help_text='Intervalo entre análises')),
                ('cache_ttl_seconds', models.IntegerField(default=10, help_text='Tempo de vida do cache de preços')),
                ('risk_tolerance', models.FloatField(default=0.5, help_text='0.0 (Conservador) a 1.0 (Arriscado)')),
                ('min_confidence_score', models.FloatField(default=0.6, help_text='Score mínimo para executar trade')),
                ('trade_size_percentage', models.FloatField(default=0.1, help_text='Percentagem da banca por trade (ex: 0.1 = 10%)')),
                ('trade_size_amount', models.DecimalField(blank=True, decimal_places=8, help_text='Valor fixo opcional (se definido, ignora a percentagem)', max_digits=20, null=True)),
                ('cleanup_keep_count', models.IntegerField(default=100, help_text='Número de trades a manter no histórico')),
            ],
            options={
                'verbose_name': 'Configuração do Bot',
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(db_index=True, max_length=20)),
                ('bid', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_symbol', models.CharField(help_text='Ex: BTC-USD', max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('target_allocation', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('operation', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_at_execution', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(default='EXECUTED', max_length=20)),
                ('confidence_score', models.FloatField(null=True)),
                ('reason', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
