# Generated by Django 6.0.2 on 2026-02-14 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('risk_tolerance', models.FloatField(default=0.5, help_text='Risk tolerance (0.0=very conservative, 1.0=aggressive)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('min_confidence_score', models.FloatField(default=0.7, help_text='Minimum confidence to execute trade', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('trade_size_amount', models.DecimalField(blank=True, decimal_places=8, help_text='Fixed amount per trade (if percentage not set)', max_digits=15, null=True)),
                ('trade_size_percentage', models.FloatField(default=0.1, help_text='Percentage of holdings to trade (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('check_interval_seconds', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('cache_ttl_seconds', models.IntegerField(default=3, help_text='Price cache time-to-live in seconds', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bot Config',
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_symbol', models.CharField(max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'pair_symbol'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(db_index=True, max_length=20)),
                ('bid', models.DecimalField(decimal_places=8, max_digits=15)),
                ('ask', models.DecimalField(decimal_places=8, max_digits=15)),
                ('last', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['pair', '-updated_at'], name='finance_pri_pair_5ea659_idx')],
                'unique_together': {('pair',)},
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_pair', models.CharField(max_length=20)),
                ('to_pair', models.CharField(max_length=20)),
                ('decision', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('NONE', 'No Action')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('from_price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('to_price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('risk_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('volatility', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='finance_tra_created_a4fb3f_idx')],
            },
        ),
    ]
