# Generated by Django 6.0.2 on 2026-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpool',
            name='target_location',
        ),
        migrations.AddField(
            model_name='assetpool',
            name='target_allocation',
            field=models.FloatField(default=0.0),
        ),
    ]
