# Generated by Django 6.0.2 on 2026-02-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricesnapshot',
            name='last',
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
