# Generated by Django 6.0.2 on 2026-02-15 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_pricesnapshot2_pricesnapshot3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceSnapshot2',
        ),
        migrations.DeleteModel(
            name='PriceSnapshot3',
        ),
    ]
