# Generated by Django 6.0.2 on 2026-02-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_delete_pricesnapshot2_delete_pricesnapshot3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='operation',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='price_at_execution',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
