# Generated by Django 6.0.2 on 2026-02-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_tradehistory_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
