# Generated by Django 6.0.2 on 2026-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_botconfig_bot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="User's investment amount", max_digits=20),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='selected_currencies',
            field=models.CharField(default='BTC,ETH,EUR,USD', help_text='Comma-separated list of selected currency symbols', max_length=200),
        ),
    ]
