# Generated by Django 6.0.2 on 2026-02-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_botconfig_investment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesnapshot',
            name='source',
            field=models.CharField(default='uphold', max_length=30),
        ),
    ]
